### ISSUE TITLE
 Cannot find module 'longest

### ISSUE THREAD

**Issue by simplepry-s** [blacktiny/isomorphic-react-redux-admin-dashboard#1]
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: D:\workspace\km\isomorphic-react-redux-admin-dashboard\node_modules\optipng-bin
Output:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'longest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\workspace\km\isomorphic-react-redux-admin-dashboard\node_modules\lpad-align\index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by simplepry-s** [comment]
got error after yarn install
