### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by criticalsoft** [blacktiny/isomorphic-react-redux-admin-dashboard#2]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\IsomorphicDashBoard\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\IsomorphicDashBoard\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=D:\\IsomorphicDashBoard\\node_modules\\@firebase\\firestore\\node_modules\\grpc\\src\\node\\extension_binary\\node-v93-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=D:\\IsomorphicDashBoard\\node_modules\\@firebase\\firestore\\node_modules\\grpc\\src\\node\\extension_binary\\node-v93-win32-x64-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
gyp ERR! cwd D:\IsomorphicDashBoard\node_modules\@firebase\firestore\node_modules\grpc
gyp ERR! node -v v16.11.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\IsomorphicDashBoard\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=D:\IsomorphicDashBoard\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=D:\IsomorphicDashBoard\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\IsomorphicDashBoard\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Windows_NT 10.0.19042
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\IsomorphicDashBoard\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd D:\IsomorphicDashBoard\node_modules\@firebase\firestore\node_modules\grpc
node-pre-gyp ERR! node -v v16.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe D:\IsomorphicDashBoard\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --library=static_library --module=D:\IsomorphicDashBoard\node_modules\@firebase\firestore\node_modules\grpc\src\node\extension_binary\node-v93-win32-x64-unknown\grpc_node.node --module_name=grp

**Comment by criticalsoft** [comment]
Solved By:
yarn upgrade

**Comment by criticalsoft** [comment]
By The Way You Are Really Skilled.
