### ISSUE TITLE
Build Error 2021

### ISSUE THREAD

**Issue by criticalsoft** [blacktiny/isomorphic-react-redux-admin-dashboard#3]
PS D:\IsomorphicDashBoard> yarn build:iso-cra
yarn run v1.7.0
$ yarn workspace isomorphic run build
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.

D:\IsomorphicDashBoard\shared\common\UI\SwiperSlider\index.js
Cannot find module: 'react-id-swiper/lib/styles/css/swiper.css'. Make sure this package is installed.

You can install this package by running: yarn add react-id-swiper/lib/styles/css/swiper.css.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files (x86)\Yarn\lib\cli.js run build
Directory: D:\IsomorphicDashBoard\packages\isomorphic
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\IsomorphicDashBoard> yarn build:iso-next
yarn run v1.7.0
$ yarn workspace isomorphicnext run build
$ next build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

info  - Using external babel configuration from D:\IsomorphicDashBoard\packages\isomorphic-next\babel.config.js
info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'react-id-swiper/lib/styles/css/swiper.css' in 'D:\IsomorphicDashBoard\node_modules\@iso\ui\SwiperSlider'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (D:\IsomorphicDashBoard\node_modules\next\dist\build\index.js:15:918)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files (x86)\Yarn\lib\cli.js run build
Directory: D:\IsomorphicDashBoard\packages\isomorphic-next
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\IsomorphicDashBoard> yarn build:iso-boilerplate
yarn run v1.7.0
$ yarn workspace isomorphic-boilerplate run build
$ react-app-rewired build
Creating an optimized production build...
Compiled with warnings.

./src/containers/Topbar/Topbar.js
  Line 16:10:  'selectedItem' is assigned a value but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  251.51 KB  build\static\js\1.c151a626.chunk.js
  165.26 KB  build\static\js\0.9e839135.chunk.js
  155.33 KB  build\static\js\7.e5e36803.chunk.js
  150 KB     build\static\js\3.35974156.chunk.js
  60.16 KB   build\static\js\main.176dac23.chunk.js
  37.91 KB   build\static\js\8.066698b7.chunk.js
  21.7 KB    build\static\js\2.742974ce.chunk.js
  18.82 KB   build\static\js\11.a7f63483.chunk.js
  6.88 KB    build\static\js\4.dd118588.chunk.js
  6.57 KB    build\static\js\9.02fdbb42.chunk.js
  6.04 KB    build\static\css\2.4e70d2f0.chunk.css
  5.79 KB    build\static\js\10.bedb719e.chunk.js
  4.42 KB    build\static\css\8.a12eccf6.chunk.css
  4.04 KB    build\static\css\0.23bd66dc.chunk.css
  1.66 KB    build\static\js\runtime-main.3ba0446b.js
  1.08 KB    build\static\css\3.fdcc8277.chunk.css
  1.06 KB    build\static\js\14.73aee1c8.chunk.js
  1.03 KB    build\static\css\10.617067d5.chunk.css
  1.03 KB    build\static\css\1.617067d5.chunk.css
  727 B      build\static\js\13.bd6cbd43.chunk.js
  707 B      build\static\js\12.daa39c7d.chunk.js
  69 B       build\static\css\7.0ef9204e.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

Done in 30.21s.
PS D:\IsomorphicDashBoard>
PS D:\IsomorphicDashBoard> yarn build:hotel
yarn run v1.7.0
$ yarn workspace hotel run build
warning package.json: No license field
$ react-app-rewired build
Creating an optimized production build...
Failed to compile.

.\src\container\Agent\AccountSettings\AgentAccountSettingsPage.js
Cannot find module: '@isomorphic/shared/hotel/assets/images/profileImage.jpg'. Make sure this package is installed.

You can install this package by running: yarn add @isomorphic/shared/hotel/assets/images/profileImage.jpg.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files (x86)\Yarn\lib\cli.js run build
Directory: D:\IsomorphicDashBoard\packages\hotel
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\IsomorphicDashBoard> yarn build:hotel-next
yarn run v1.7.0
$ yarn workspace hotel-next run build
warning package.json: No license field
$ next build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

info  - Using external babel configuration from D:\IsomorphicDashBoard\packages\hotel-next\babel.config.js
info  - Creating an optimized production build
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve '@isomorphic/shared/hotel/assets/images/favicon.png' in 'D:\IsomorphicDashBoard\packages\hotel-next\pages'

> Build error occurred
Error: > Build failed because of webpack errors
    at build (D:\IsomorphicDashBoard\node_modules\next\dist\build\index.js:15:918)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: C:\Program Files (x86)\Yarn\lib\cli.js run build
Directory: D:\IsomorphicDashBoard\packages\hotel-next
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by criticalsoft** [comment]
Solved By:
// import 'react-id-swiper/lib/styles/css/swiper.css';
import 'swiper/css/swiper.css'




// process.env.BUNDLE_VISUALIZE === 1 && addBundleVisualizer(),
addBundleVisualizer(),

// "build": "BUNDLE_VISUALIZE=1 react-app-rewired build",
"build": "react-app-rewired build",




// @isomorphic/shared/hotel/
@hotel/
